
CREATE TABLE PUBLIC.PERSONA(
    CODIGO_PERSONA BIGINT  NOT NULL,
    GENERO  VARCHAR(255),
    IDENTIFICACION VARCHAR(255),
    NOMBRE VARCHAR(255)
);
CREATE TABLE PUBLIC.CLIENTE(
    CODIGO_CLIENTE BIGINT NOT NULL,
    CONTRASENIA VARCHAR(255),
    ESTADO BOOLEAN,
    CODIGO_PERSONA BIGINT NOT NULL
);
ALTER TABLE PUBLIC.PERSONA ADD CONSTRAINT PK_PERSONA PRIMARY KEY(CODIGO_PERSONA);
ALTER TABLE PUBLIC.CLIENTE ADD CONSTRAINT PK_CLIENTE PRIMARY KEY(CODIGO_CLIENTE);
ALTER TABLE PUBLIC.CLIENTE ADD CONSTRAINT FK_PERSONA_CLIENTE FOREIGN KEY(CODIGO_PERSONA) REFERENCES PUBLIC.PERSONA(CODIGO_PERSONA) NOCHECK;